name: V2Ray Scraper Auto Update

on:
  schedule:
    - cron: "0 */12 * * *"  # هر 12 ساعت
  workflow_dispatch:  # اجرای دستی

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run scraper script
      run: python config_scraper.py

    - name: Commit and push results
      run: |
        git config user.name "Sm Neverland"
        git config user.email "iamdaryoush@gmail.com"
        git add v2ray_configs.txt
        git commit -m "Updated v2ray configs by Sm Neverland"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/onlythink/sm_neverland_v2ray_subscribe.git HEAD:main
